class DataIngestionArtifact:
    pass
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainigArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...